### ISSUE TITLE
Research methods to visualize/graph functions (Big O time complexities)

### ISSUE THREAD

**Issue by IanW23** [Alexw360/Virtual-TA#15]

**Comment by Arif-Nas** [comment]
Out RESTful API in the backend cna be used to take complexities and handle the interaction of using one of the following libraries to visualize a graph function.

D3.JS, Chart.JS, and Vis.JS are all solid options that can render dynamic interfactive graph visualizations. Chart is perhaps the simplest but still quite powerful, D3 is highly customizeable and data-drive, might be overkill for this applications.

Recharts Nivo and Victory are react libraries that that will work well with out current tech stack to provide the visualizations as interactive graphs. Recharts and Nivo are built on D3 and have various components that make the integration possible.

To handle an interactive component with the visualizations instead of just displaying a graph our backend can utilize wbesockets to facilitate the realtime updates for the visualization.

Next steps will be to prototype the functionality on a new branch.
